baseURL = "https://makezurich.ch/"
title = "Make Zurich 2020"
theme = "hugo-hackatheme"
languageCode = "en-us"
defaultContentLanguage = "en"
disableLanguages = ["de"]
enableMissingTranslationPlaceholders = false    # If you're adding a new translation languange, you might want to set the following to true

[params]
dateStart = 2020-03-20T18:00:00+02:00           # Required
dateEnd = 2020-03-28T22:00:00+02:00             # Required
dateForm = "January 2, 2006"                    # Required, defines date formatting style (see Hugo dateFormat)
hashtag = "MakeZurich"

[params.license]                                # Optional, but highly recommended
name = "CC-BY-SA 4.0"
url = "https://github.com/make-zurich/website/blob/master/LICENSE"

[params.styling]
backgroundHero = "/images/background.jpg"           # Required
logoHero = "/images/logo-inv.png"                   # Required
logoNavbar = "/images/logo.svg"                     # Optional, leave empty to show no logo on navbar
externalImage = "/images/externals/event-cover.png" # Optional, used for sharing meta data
themeColor = "#ffffff"                              # Optional
customCSS = "/css/styles.css"                       # Optional, remove/leave empty if you don't need custom styles

# Venue description
# Details are used to generate maps and schema.org meta-data
[params.venue]
name = "Impact Hub Viadukt Bogen D"
street = "Viaduktstrasse 93"
zipCode = "8005"
city = "Zürich"
state = "Zürich"
country = "Switzerland"
mapboxPublicToken = "pk.eyJ1IjoiZ29uemFsb2Nhc2FzIiwiYSI6ImNpa2JnMDI2cDAwMzR3bGx2eXkyZDh4a3QifQ.sgne64JeXpvQee49WW1oTA"
mapboxStyle = "emerald"
mapboxZoom = 15

[params.venue.coords]
latitude = 47.3848764
longitude = 8.5209667

# Registration
[params.registration]
registrationForm = "https://www.eventbrite.com/e/make-zurich-2020-civic-tech-hackathon-registration-87045658909?ref=estw"

# Organizers of the event: add as many as you need.
[[params.organizers]]
name = "Stadt Zürich"
logo = "/images/logo-zurich.png"
url = "https://www.stadt-zuerich.ch"

[[params.organizers]]
name = "Open Network Infrastructure Association"
logo = "/images/logo-onia.png"
url = "https://opennetworkinfrastructure.org"

# Team
[params.team]
order = "random"                                # Optional, to maintain the ordering as specified, remove or set to "fixed"

[[params.team.members]]
name = "Francesca Sanfilippo"
photo = "/images/team/francesca.png"

[[params.team.members]]
name = "Gonzalo Casas"
photo = "/images/team/gnz.png"

[[params.team.members]]
name = "Marcus Cathomen"
photo = "/images/team/marcus.png"

[[params.team.members]]
name = "Simon Maurer"
photo = "/images/team/simon.png"

[[params.team.members]]
name = "Michel Racic"
photo = "/images/team/michel.png"

[[params.team.members]]
name = "Oleg Lavrovsky"
photo = "/images/team/oleg.png"

[[params.team.members]]
name = "Tillo Bosshart"
photo = "/images/team/tillo.png"

[[params.team.members]]
name = "Dirk Zugenmaier"
photo = "/images/team/dirk.png"

[[params.team.members]]
name = "Diego Sandoval"
photo = "/images/team/diego.png"

[[params.team.members]]
name = "Yannick Weiss"
photo = "/images/team/yannick.png"

[[params.team.members]]
name = "Urs Marti"
photo = "/images/team/urs.png"

[[params.team.members]]
name = "Alexandra Collm"
photo = "/images/team/alexandra.png"

# Sponsors of the event
[[params.partners.sponsors]]
name = "Stadt Zurich"
logo = "/images/partners/logo-stez.png"
url = "https://www.stadt-zuerich.ch/prd/de/index/stadtentwicklung.html"
class = "my-2 w-50"

[[params.partners.sponsors]]
name = "EWZ"
logo = "/images/partners/logo-ewz.png"
url = "https://www.ewz.ch"
class = "w-50"

[[params.partners.sponsors]]
name = "u-blox"
logo = "/images/partners/logo-u-blox.png"
url = "https://www.u-blox.ch"
class = "my-1 w-50"

[[params.partners.sponsors]]
name = "Sensirion"
logo = "/images/partners/logo-sensirion.png"
url = "https://www.sensirion.com/en/"
class = "my-3 w-50"

[[params.partners.sponsors]]
name = "Miromico GmbH"
logo = "/images/partners/logo-miromico.png"
url = "https://miromico.ch/"
class = "my-1 w-50"

[[params.partners.sponsors]]
name = "swissdevjobs.ch"
logo = "/images/partners/logo-swissdevjobs.png"
url = "https://swissdevjobs.ch/jobs/All/Zurich"
class = "my-1 w-50"


# Community partners of the event
[[params.partners.community]]
name = "The Things Network"
logo = "/images/partners/logo-ttn.png"
url = "https://www.thethingsnetwork.org/"
class = "w-50"

[[params.partners.community]]
name = "IoT Zurich"
logo = "/images/partners/logo-iotzh.png"
url = "https://www.meetup.com/IoT-Zurich"
class = "my-3 w-50"

[[params.partners.community]]
name = "opendata.ch"
logo = "/images/partners/logo-opendatach.png"
url = "http://make.opendata.ch/"
class = "my-2 h-50"

[[params.partners.community]]
name = "SGMK"
logo = "/images/partners/logo-sgmk.png"
url = "https://www.mechatronicart.ch/"
class = "my-2 h-50"

# [[params.partners.community]]
# name = "Women++"
# logo = "/images/partners/logo-womenplusplus.png"
# url = "https://www.womenplusplus.ch/"
# class = "my-3 w-50"

# [[params.partners.community]]
# name = "GDG Zurich"
# logo = "/images/partners/logo-gdg.png"
# url = "http://www.gdgzh.ch/"
# class = "my-3 w-50"

# [[params.partners.community]]
# name = "Women Techmakers Switzerland"
# logo = "/images/partners/logo-wtm.png"
# url = "https://www.meetup.com/wtm-switzerland/"
# class = "my-3 w-25"

# [[params.partners.community]]
# name = "SWITCH.CH"
# logo = "/images/partners/logo-switch.png"
# url = "https://www.switch.ch/"
# class = "my-4 w-50"

# Challenges: add heading images, url and key
# and then add localizations according that key
[[params.challenges]]
image = "/images/challenges/granny.png"
# url = "/box/1"
i18n = "saw"

[[params.challenges]]
image = "/images/challenges/move-chill.png"
# url = "/box/2"
i18n = "taz1"

[[params.challenges]]
image = "/images/challenges/breathe.png"
# url = "/box/3"
i18n = "ttn"

[[params.challenges]]
image = "/images/challenges/bicycle-parking.png"
# url = "/box/4"
i18n = "taz2"

[[params.challenges]]
image = "/images/challenges/open.png"
# url = "/box/7"
i18n = "open"

# Social links: add as many as you need.
# Here's a list of the most popular fa-icons:
# [fa-facebook-square, fa-twitter-square, fa-instagram, fa-google-plus-square, fa-linkedin-square, fa-tumblr-square, fa-github, fa-envelope]
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/makezurich"
    text = "@makezurich"
    icon = "fa-twitter-square"

[[params.social]]
	title = "github"
	url = "https://github.com/make-zurich"
    text = "github.com/make-zurich"
    icon = "fa-github"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/events/2615070568610092"
    text = "Open Network Infrastructure Association"
    icon = "fa-facebook-square"

[[params.social]]
	title = "instagram"
	url = "https://instagram.com/makezurich"
    text = "@makezurich"
    icon = "fa-instagram"

[[params.social]]
	title = "email"
	url = "mailto:info@makezurich.ch"
    text = "info@makezurich.ch"
    icon = "fa-envelope"

# SEO Options: all verification codes are optional
[params.seo.verification]
    google = ""
    bing = ""
    alexa = ""
    yandex = ""

[languages]
[languages.en]
weight = 1
languageName = "English"

[[languages.en.menu.main]]
    name = "Schedule"
    url = "/#schedule"
    weight = 2

[[languages.en.menu.main]]
    name = "Venue"
    url = "/#venue"
    weight = 3

[[languages.en.menu.main]]
    name = "Challenges"
    url = "/#challenges"
    weight = 4

# NOTE: Primary button link (Navigation)
# Change links according to event stage:
# Before event=Register
# During event=Getting Started
# After=Projects
[[languages.en.menu.highlighted]]
    # BEFORE
    name = "Register"
    url = "/register"
    # DURING
    # name = "Getting started"
    # url = "/start"
    # AFTER
    # name = "Projects"
    # url = "https://now.makezurich.ch/event/4"
    weight = 5
    pre = "btn-black"
    post = "fa-sign-in"

# NOTE: Primary button link (Hero)
# Same as the one above
[[languages.en.menu.hero]]
    name = "Register"
    url = "#register"
    pre = "event-primary-color"
    post = "fa-sign-in"

[languages.de]
weight = 2
languageName = "Deutsch"

[[languages.de.menu.main]]
    name = "Zeitplan"
    url = "/#schedule"
    weight = 2

[[languages.de.menu.main]]
    name = "Venue"
    url = "/#venue"
    weight = 3

[[languages.de.menu.main]]
    name = "Challenges"
    url = "/#challenges"
    weight = 4

# NOTE: Primary button link (Navigation)
# Change links according to event stage:
# Before event=Register
# During event=Getting Started
# After=Projects
[[languages.de.menu.highlighted]]
    # BEFORE
    name = "Anmelden"
    url = "/register"
    # DURING
    # name = "Getting started"
    # url = "/de/start"
    # AFTER
    # name = "Projekte"
    # url = "https://now.makezurich.ch/event/4"
    weight = 5
    pre = "btn-black"
    post = "fa-sign-in"

# NOTE: Primary button link (Hero)
# Same as the one above
[[languages.de.menu.hero]]
    name = "Anmelden"
    url = "#register"
    pre = "event-primary-color"
    post = "fa-sign-in"

# Hugo's Markdown rendering engine options
[blackfriday]
hrefTargetBlank = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
