baseURL = "https://makezurich.ch/"
title = "Make Zurich Vol. II"
theme = "hugo-hackatheme"
languageCode = "en-us"
defaultContentLanguage = "en"
disableLanguages = ["de"]
googleAnalytics = "UA-166167-5"                 # Change this to invalid on the exampleSite
enableMissingTranslationPlaceholders = false    # If you're adding a new translation languange, you might want to set the following to true

[params]
dateStart = 2018-06-22T18:00:00+02:00           # Required
dateEnd = 2018-06-30T22:00:00+02:00             # Required
dateForm = "January 2, 2006"                    # Required, defines date formatting style (see Hugo dateFormat)
hashtag = "MakeZurich"

[params.license]                                # Optional, but highly recommended
name = "CC-BY-SA 4.0"
url = "https://github.com/make-zurich/website/blob/master/LICENSE"

[params.styling]
backgroundHero = "/images/background.jpg"           # Required
logoHero = "/images/logo-inv.png"                   # Required
logoNavbar = "/images/logo.svg"                     # Optional, leave empty to show no logo on navbar
externalImage = "/images/externals/event-cover.png" # Optional, used for sharing meta data
themeColor = "#ffffff"                              # Optional
# customCSS = "/css/styles.css"                     # Optional, remove/leave empty if you don't need custom styles

# Venue description
# Details are used to generate maps and schema.org meta-data
[params.venue]
name = "Kraftwerk"
street = "Selnaustrasse 25"
zipCode = "8001"
city = "Zürich"
state = "Zürich"
country = "Switzerland"
mapboxPublicToken = "pk.eyJ1IjoiZ29uemFsb2Nhc2FzIiwiYSI6ImNpa2JnMDI2cDAwMzR3bGx2eXkyZDh4a3QifQ.sgne64JeXpvQee49WW1oTA"
mapboxStyle = "emerald"
mapboxZoom = 16

[params.venue.coords]
latitude = 47.3722277
longitude = 8.53201869999993

# Registration
[params.registration]
registrationForm = "https://www.eventbrite.com/e/make-zurich-vol-ii-civic-tech-hackathon-registration-45872940199"

# Organizers of the event: add as many as you need.
[[params.organizers]]
name = "Stadt Zürich"
logo = "/images/logo-zurich.png"
url = "https://www.stadt-zuerich.ch"

[[params.organizers]]
name = "Open Network Infrastructure Association"
logo = "/images/logo-onia.png"
url = "https://opennetworkinfrastructure.org"

# Team
[params.team]
order = "random"                                # Optional, to maintain the ordering as specified, remove or set to "fixed"

[[params.team.members]]
name = "Gonzalo Casas"
photo = "/images/team/gnz.png"

[[params.team.members]]
name = "Christina Rieder"
photo = "/images/team/christina.png"

[[params.team.members]]
name = "Urs Marti"
photo = "/images/team/urs.png"

[[params.team.members]]
name = "Reto Wick"
photo = "/images/team/reto.png"

[[params.team.members]]
name = "Marcus Cathomen"
photo = "/images/team/marcus.png"

[[params.team.members]]
name = "Muriel Buri"
photo = "/images/team/muriel.png"

[[params.team.members]]
name = "Simon Maurer"
photo = "/images/team/simon.png"

[[params.team.members]]
name = "Alexandra Collm"
photo = "/images/team/alexandra.png"

[[params.team.members]]
name = "Marco Sieber"
photo = "/images/team/marco.png"

[[params.team.members]]
name = "Michel Racic"
photo = "/images/team/michel.png"

[[params.team.members]]
name = "Oleg Lavrovsky"
photo = "/images/team/oleg.png"

[[params.team.members]]
name = "Dirk Zugenmaier"
photo = "/images/team/dirk.png"

[[params.team.members]]
name = "Tillo Bosshart"
photo = "/images/team/tillo.png"

# Missing pictures:
# [ ] Baxter Yazbek
# [ ] Afsoon Ebrahimi
# [ ] Lukas Limacher
# [ ] Thomas Amberg
# [ ] Benjamin Marty
# [ ] Oliver Walkhoff
# [ ] Robert Fey
# [ ] Filippo Broggini
# [ ] Benno Seiler

# Sponsors of the event
[[params.partners.sponsors]]
name = "Stadt Zurich"
logo = "/images/partners/logo-odz.png"
url = "https://stadt-zuerich.ch/opendata"
class = "my-2 w-50"

[[params.partners.sponsors]]
name = "EWZ"
logo = "/images/partners/logo-ewz.png"
url = "https://www.ewz.ch"
class = "w-50"

[[params.partners.sponsors]]
name = "u-blox"
logo = "/images/partners/logo-u-blox.png"
url = "https://www.u-blox.ch"
class = "my-1 w-50"

[[params.partners.sponsors]]
name = "Sensirion"
logo = "/images/partners/logo-sensirion.png"
url = "https://www.sensirion.com/en/"
class = "my-3 w-50"

[[params.partners.sponsors]]
name = "Hivemind AG"
logo = "/images/partners/logo-hivemind.png"
url = "https://www.hivemind.ch"
class = "w-50"

[[params.partners.sponsors]]
name = "Nine"
logo = "/images/partners/logo-nine.png"
url = "https://www.nine.ch"
class = "w-50"

[[params.partners.sponsors]]
name = "Avelon"
logo = "/images/partners/logo-avelon.png"
url = "https://avelon.ch"
class = "my-4 w-50"

[[params.partners.sponsors]]
name = "Axa Winterthur"
logo = "/images/partners/logo-axa.png"
url = "https://www.axa.ch"
class = "my-2 w-25"

[[params.partners.sponsors]]
name = "Pi-Shop.ch"
logo = "/images/partners/logo-pi-shop.png"
url = "https://www.pi-shop.ch/"
class = "my-4 w-50"

[[params.partners.sponsors]]
name = "Adnexo GmbH"
logo = "/images/partners/logo-adnexo.png"
url = "https://www.adnexo.ch/"
class = "my-4 w-50"

[[params.partners.sponsors]]
name = "Miromico GmbH"
logo = "/images/partners/logo-miromico.png"
url = "http://www.miromico.ch/"
class = "my-1 w-50"

[[params.partners.sponsors]]
name = "Decentlab"
logo = "/images/partners/logo-decentlab.png"
url = "https://www.decentlab.com/"
class = "my-4 w-50"

[[params.partners.sponsors]]
name = "SWITCH.CH"
logo = "/images/partners/logo-switch.png"
url = "https://www.switch.ch/"
class = "my-4 w-50"

[[params.partners.sponsors]]
name = "Rockstar"
logo = "/images/partners/logo-rockstar.png"
url = "http://www.rockstar.jobs/"
class = "my-3 w-50"

# Community partners of the event
[[params.partners.community]]
name = "The Things Network"
logo = "/images/partners/logo-ttn.png"
url = "https://www.thethingsnetwork.org/"
class = "w-50"

[[params.partners.community]]
name = "IoT Zurich"
logo = "/images/partners/logo-iotzh.png"
url = "https://www.meetup.com/IoT-Zurich"
class = "my-3 w-50"

[[params.partners.community]]
name = "opendata.ch"
logo = "/images/partners/logo-opendatach.png"
url = "http://make.opendata.ch/"
class = "my-2 h-50"

[[params.partners.community]]
name = "SGMK"
logo = "/images/partners/logo-sgmk.png"
url = "https://www.mechatronicart.ch/"
class = "my-2 h-50"

[[params.partners.community]]
name = "Women++"
logo = "/images/partners/logo-womenplusplus.png"
url = "https://www.womenplusplus.ch/"
class = "my-3 w-50"

[[params.partners.community]]
name = "GDG Zurich"
logo = "/images/partners/logo-gdg.png"
url = "http://www.gdgzh.ch/"
class = "my-3 w-50"

[[params.partners.community]]
name = "Women Techmakers Switzerland"
logo = "/images/partners/logo-wtm.png"
url = "https://www.meetup.com/wtm-switzerland/"
class = "my-3 w-25"


# Challenges: add heading images, url and key
# and then add localizations according that key
[[params.challenges]]
image = "/images/challenges/tram.png"
url = "/box/1"
i18n = "vbz"

[[params.challenges]]
image = "/images/challenges/forest.png"
url = "/box/2"
i18n = "gsz"

[[params.challenges]]
image = "/images/challenges/bike.png"
url = "/box/3"
i18n = "velo"

[[params.challenges]]
image = "/images/challenges/city.png"
url = "/box/4"
i18n = "stez"

[[params.challenges]]
image = "/images/challenges/school.png"
url = "/box/5"
i18n = "ssd"

[[params.challenges]]
image = "/images/challenges/ewz.png"
url = "/box/6"
i18n = "ewz"

[[params.challenges]]
image = "/images/challenges/open.png"
url = "/box/7"
i18n = "open"

# Social links: add as many as you need.
# Here's a list of the most popular fa-icons:
# [fa-facebook-square, fa-twitter-square, fa-instagram, fa-google-plus-square, fa-linkedin-square, fa-tumblr-square, fa-github, fa-envelope]
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/makezurich"
    text = "@makezurich"
    icon = "fa-twitter-square"

[[params.social]]
	title = "github"
	url = "https://github.com/make-zurich"
    text = "github.com/make-zurich"
    icon = "fa-github"

[[params.social]]
	title = "email"
	url = "mailto:info@makezurich.ch"
    text = "info@makezurich.ch"
    icon = "fa-envelope"

# SEO Options: all verification codes are optional
[params.seo.verification]
    google = ""
    bing = ""
    alexa = ""
    yandex = ""

[languages]
[languages.en]
weight = 1
languageName = "English"

[[languages.en.menu.main]]
    name = "Schedule"
    url = "/#schedule"
    weight = 2

[[languages.en.menu.main]]
    name = "Venue"
    url = "/#venue"
    weight = 3

[languages.de]
weight = 2
languageName = "Deutsch"

[[languages.de.menu.main]]
    name = "Schedule"
    url = "/#schedule"
    weight = 2

[[languages.de.menu.main]]
    name = "Venue"
    url = "/#venue"
    weight = 3



# Hugo's Markdown rendering engine options
[blackfriday]
hrefTargetBlank = true
